kind: pipeline
name: amd64
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: golang:1.17-alpine
    commands:
      - echo "Running tests in Go container:"
      - go version
      - echo "Installing ginkgo and application dependencies"
      - apk --no-cache add git gcc musl-dev
      - go get github.com/onsi/ginkgo/v2/ginkgo
      - go install github.com/onsi/ginkgo/v2/ginkgo
      - echo "Running tests"
      - ginkgo
